export const mockWorkouts = [
  {
    id: '1',
    ngay: '2026-04-25',
    loaiBaiTap: 'Cardio',
    thoiLuong: 45,
    caloDot: 300,
    ghiChu: 'Chạy bộ công viên',
    trangThai: 'Hoàn thành',
  },
  {
    id: '2',
    ngay: '2026-04-26',
    loaiBaiTap: 'Strength',
    thoiLuong: 60,
    caloDot: 450,
    ghiChu: 'Tập ngực và tay',
    trangThai: 'Hoàn thành',
  },
  {
    id: '3',
    ngay: '2026-04-27',
    loaiBaiTap: 'Yoga',
    thoiLuong: 30,
    caloDot: 150,
    ghiChu: 'Thư giãn buổi sáng',
    trangThai: 'Hoàn thành',
  },
  {
    id: '4',
    ngay: '2026-04-28',
    loaiBaiTap: 'HIIT',
    thoiLuong: 20,
    caloDot: 350,
    ghiChu: 'Tập cường độ cao',
    trangThai: 'Bỏ lỡ',
  },
  {
    id: '5',
    ngay: '2026-04-29',
    loaiBaiTap: 'Strength',
    thoiLuong: 50,
    caloDot: 400,
    ghiChu: 'Tập lưng và xô',
    trangThai: 'Hoàn thành',
  },
];

export const mockHealthMetrics = [
  {
    id: '1',
    ngay: '2026-04-25',
    canNang: 70,
    chieuCao: 175,
    nhipTim: 65,
    gioNgu: 8,
  },
  {
    id: '2',
    ngay: '2026-04-26',
    canNang: 69.8,
    chieuCao: 175,
    nhipTim: 64,
    gioNgu: 7.5,
  },
  {
    id: '3',
    ngay: '2026-04-27',
    canNang: 69.5,
    chieuCao: 175,
    nhipTim: 66,
    gioNgu: 8,
  },
  {
    id: '4',
    ngay: '2026-04-28',
    canNang: 69.5,
    chieuCao: 175,
    nhipTim: 62,
    gioNgu: 7,
  },
  {
    id: '5',
    ngay: '2026-04-29',
    canNang: 69.2,
    chieuCao: 175,
    nhipTim: 63,
    gioNgu: 8.5,
  },
];

export const mockGoals = [
  {
    id: '1',
    tenMucTieu: 'Giảm 5kg trong 2 tháng',
    loai: 'Giảm cân',
    giaTriMucTieu: 65,
    giaTriHienTai: 69.2,
    deadline: '2026-06-25',
    trangThai: 'Đang thực hiện',
  },
  {
    id: '2',
    tenMucTieu: 'Chạy 5km dưới 25 phút',
    loai: 'Cải thiện sức bền',
    giaTriMucTieu: 25,
    giaTriHienTai: 28,
    deadline: '2026-05-15',
    trangThai: 'Đang thực hiện',
  },
  {
    id: '3',
    tenMucTieu: 'Ngủ đủ 8 tiếng/ngày',
    loai: 'Khác',
    giaTriMucTieu: 8,
    giaTriHienTai: 7.8,
    deadline: '2026-04-30',
    trangThai: 'Đã đạt',
  },
];

export const mockExercises = [
  {
    id: '1',
    tenBaiTap: 'Push-up (Hít đất)',
    nhomCo: 'Chest',
    mucDoKho: 'Trung bình',
    moTaNgan: 'Bài tập cơ ngực cơ bản sử dụng trọng lượng cơ thể.',
    caloTieuHao: 300,
    huongDan: '1. Vào tư thế Plank cao. 2. Hạ thấp cơ thể cho đến khi ngực gần chạm sàn. 3. Đẩy người lên vị trí ban đầu.',
  },
  {
    id: '2',
    tenBaiTap: 'Squat',
    nhomCo: 'Legs',
    mucDoKho: 'Dễ',
    moTaNgan: 'Bài tập phát triển sức mạnh phần thân dưới, đặc biệt là đùi và mông.',
    caloTieuHao: 400,
    huongDan: '1. Đứng thẳng, hai chân rộng bằng vai. 2. Hạ hông xuống như đang ngồi ghế. 3. Đứng thẳng lên vị trí ban đầu.',
  },
  {
    id: '3',
    tenBaiTap: 'Pull-up (Kéo xà)',
    nhomCo: 'Back',
    mucDoKho: 'Khó',
    moTaNgan: 'Bài tập cơ xô và lưng rất hiệu quả.',
    caloTieuHao: 450,
    huongDan: '1. Nắm xà, lòng bàn tay hướng về trước hoặc sau. 2. Kéo người lên cho đến khi cằm qua xà. 3. Hạ xuống từ từ.',
  },
  {
    id: '4',
    tenBaiTap: 'Plank',
    nhomCo: 'Core',
    mucDoKho: 'Dễ',
    moTaNgan: 'Giữ cơ thể trên một đường thẳng để tăng cường cơ lõi.',
    caloTieuHao: 200,
    huongDan: '1. Nằm sấp, chống khuỷu tay xuống sàn. 2. Nâng cơ thể lên sao cho thành một đường thẳng từ đầu đến gót chân. 3. Giữ tư thế.',
  },
  {
    id: '5',
    tenBaiTap: 'Burpees',
    nhomCo: 'Full Body',
    mucDoKho: 'Khó',
    moTaNgan: 'Bài tập toàn thân đốt mỡ cực tốt.',
    caloTieuHao: 600,
    huongDan: '1. Đứng thẳng. 2. Ngồi xổm, chống hai tay xuống sàn. 3. Nhảy hai chân về sau thành tư thế hít đất. 4. Nhảy hai chân về lại và đứng lên/bật nhảy.',
  },
];
